### ISSUE TITLE
Search bars -- As a user, when I search for a new streamer or a new card the search bar auto fills the best guess

### ISSUE THREAD

**Issue by Mezran** [Mezran/GT-Project01-teamPink#5]
- [x] As the user searches for a streamer, the input bar will attempt to auto complete the search result
- [x] As the user searches for a new card, the input bar will attempt to auto complete the search result

**Comment by EricBillings** [comment]
The code that I'm using has a cool feature of making the search string of the user bold and concatenating it with matches in the array.  Ex: the user types in "back" and the search autocomplete looks like **Back**stab.  Our reset.css is killing this feature, so I commented out the part of the reset that makes fonts styles be inherited by parent.  Could be an issue for other elements.
